language: objective-c
osx_image: xcode9.2
#xcode_sdk: iphonesimulator11.2
#xcode_project: LoopKit.xcodeproj
xcode_scheme:
    - LoopKit
    - LoopKitUI
script:
   - xcodebuild -project LoopKit.xcodeproj -scheme LoopKit build -destination 'name=iPhone SE' test
   - xcodebuild -project LoopKit.xcodeproj -scheme LoopKitUI  build -destination 'name=iPhone SE'
